Feat: Do all 13 sprint homework
BLADBORNE/java-shareit pull request #1
Opened 2024-05-22 13:24 UTC by BLADBORNE

2024-05-22 19:52 UTC, andrew-larkin requested changes
Привет! Отличный старт, по архитектуре все корректно, остается местами подправить и сможем двигаться дальше.

2024-05-22 19:52 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +public class Booking {
для моделей-сущностей также важен NoArgsConstructor

2024-05-22 19:52 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final ItemServiceImpl itemService;
внедряем именно интерфейс

2024-05-22 19:52 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item createNewItem(@RequestHeader("X-Sharer-User-Id") int userId, @Valid @RequestBody Item item) {
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.createItem(itemDto, userId));
Для всех методов во всех контроллерах стоит его добавить

2024-05-22 19:52 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item getItemById(@RequestHeader("X-Sharer-User-Id") int userId, @PathVariable(value = "itemId") int itemId) {
параметры в методах контроллера лучше делать врапперами, потому что если мы передадим null, то это приведет к NPE. в случае с враппером мы сможем проверить его на null

2024-05-22 19:52 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private ItemRequest request;
в dto в случае с другими классами можно использовать только id, либо другие dto

2024-05-22 19:52 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
для этого приложения давай добавим библиотеку mapStruct - она используется на всех реальных проектах, будет очень полезно ее изучить. Все методы маппинга будут писаться в одну строчку благодаря ней, и нам это очень облегчит работу над этим приложением в ближайших спринтах

2024-05-22 20:21 UTC, BLADBORNE commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +public class Booking {
Зачем ? Мы же ничего не делаем

2024-05-24 14:45 UTC, andrew-larkin reviewed
Привет! Местами еще требуется доработать.

2024-05-24 14:45 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Item createNewItem(@RequestHeader("X-Sharer-User-Id") Integer userId, @Valid @RequestBody Item item) {
нет, возвращаем в контроллере только dto

2024-05-24 14:45 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private ItemRequest request;
в dto нельзя использовать сущности-модели, только другие dto или id

2024-05-24 14:45 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public User getUserById(@PathVariable(value = "userId", required = false) Integer userId) {
1) возвращаем в ответе контроллера только dto. 2) ответ будет таким: ResponseEntity<UserDto> getUserById(). - таким образом нужно поправить по всех методах

2024-05-24 14:45 UTC, andrew-larkin requested changes
Привет! Местами еще требуется доработать.

2024-05-26 15:23 UTC, andrew-larkin approved these changes
Привет! Отлично, работа принята!

2024-05-26 20:00 UTC, merged