Do all 14 sprint homework
BLADBORNE/java-shareit pull request #2
Opened 2024-06-18 21:56 UTC by BLADBORNE

2024-06-19 15:42 UTC, andrew-larkin requested changes
Привет! Оставил комменты по коду в основном для bookin, но эти комменты актуальны для всех остальных модулей.

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingDto createBooking(
предлагаю добавить в контроллеры ResponseEntity - в 16 спринте будем строить restTemplate, через который будет идти обращение в это приложение и обернутый в ResponseEntity ответ - то что нам будет нужно

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        pastDateCheck(booking.getStart(), booking.getEnd());
в контроллерах не должно быть никакой логики кроме вызова методов сервиса и логгирования

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        BookingDto bookingDto = BookingMapper.toBookingDto(bookingService
маппинг также перенести в сервис

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        if (state.isEmpty()) {
все это перенести в сервис

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(value = "state", required = false) Optional<String> state
optional можно не добавлять к параметрам метода контроллера

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingErrorController.java
> +@RestControllerAdvice(value = "ru.practicum.shareit.booking.controller")
в целом, нам будет достаточно одного адвайсера для обработки ошибок на все сервисы

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
в dto нельзя использовать объекты-сущности. только id или другие dto

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +public class BookingMapper {
советую попробовать использовать mapStruct

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne(fetch = FetchType.EAGER)
eager для этого приложения можно не использоваться

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +
желательно тут также указывать @Repository

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(value = "SELECT * FROM bookings AS b WHERE b.item_id = ?1 AND b.start_date <= CURRENT_TIMESTAMP " +
nativeQuery - неплохое решение, но если вдруг у нас изменится БД, эти запросы могут не отработать

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking getTheClosestBookingForItem(int itemId);
из БД не стоит возвращать голый объект из-за возможности получить NPE. лучше обернуть его в Optional

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/service/ItemBookingService.java
> +    ItemBooking getTheClosestBookingForItem(int userId, int itemId);
эти методы стоит перенести просто в itemRepository

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/service/UserBookingService.java
> +public interface UserBookingService {
это функционал стоит поместить либо в booking, либо в item

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/comment/controller/CommentController.java
> +public class CommentController {
для всех контроллеров акутальны комменты из BookingController

2024-06-19 15:42 UTC, andrew-larkin commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=ci,test
закомментированный код удаляем

2024-06-19 18:54 UTC, BLADBORNE commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        BookingDto bookingDto = BookingMapper.toBookingDto(bookingService
Ссылаюсь на наставника: я специально спросил по поводу dto, мне Артур сказал, что в контроллере правильнее делать преобразования

2024-06-20 09:46 UTC, BLADBORNE commented on src/main/java/ru/practicum/shareit/booking/service/UserBookingService.java
> +public interface UserBookingService {
Тут не согласен, мы получаем бронирование, а не вещь, эта логика относится к бронированию, соответственно должно быть все в бронировании

2024-06-21 08:01 UTC, merged